apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apigateways.traffic-manager.io
spec:
  group: traffic-manager.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                defaultBackend:
                  type: string
                rules:
                  type: array
                  items:
                    type: object
                    properties:
                      match:
                        type: object
                        properties:
                          header:
                            type: string
                          value:
                            type: string
                      backend:
                        type: string
  scope: Namespaced
  names:
    plural: apigateways
    singular: apigateway
    kind: APIGateway
    shortNames:
      - agw 